DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(ID INT PRIMARY KEY, USERNAME VARCHAR(255), PASSWORD VARCHAR(255));
INSERT INTO USERS VALUES(1, 'user1', 'password');
INSERT INTO USERS VALUES(2, 'user2', 'password');

DROP TABLE IF EXISTS USER_ROLES;
CREATE TABLE USER_ROLES(ID INT PRIMARY KEY, USERNAME VARCHAR(255),  ROLE VARCHAR(255));
INSERT INTO USER_ROLES VALUES(1, 'user1', 'user');
INSERT INTO USER_ROLES VALUES(2, 'user2', 'user');